### PR TITLE
Bump electron version to 1.2.2

### PR DESCRIPTION
**Pull request by devsli**
#17 rebased to `develop`

### CODE REVIEW

**Comment by stephnr** [comment]
@devsli there was an issue with the installation step. Please resolve in a new commit. (no need for a new PR)

**Comment by andrewjaykeller** [comment]
@Stephn-R @devsli seeing it here too. Could this have to do with #14 ?

**Comment by andrewjaykeller** [comment]
Hey y'all just got his install here are my notes:

PS: Running on a fresh computer where this repo has never ran before!

```
git clone https://github.com/Stephn-R/electron-angular-boilerplate.git
git remote rename origin upstream
git remote add origin https://github.com/pushtheworldllc/electron-angular-boilerplate.git
git fetch upstream pull/17/head:electron-1.2.2
git checkout electron-1.2.2
./scripts/load_globals.sh
sudo npm install --python=python2.7
npm start
```

Errors out:

```
$ npm start

> electron-angular-boilerplate@1.5.0 start /Users/andrewkeller/dev/electron-angular-boilerplate
> gulp && electron .

[10:52:45] Using gulpfile ~/dev/electron-angular-boilerplate/gulpfile.js
[10:52:45] Starting 'build-sass'...
[10:52:45] Starting 'inject-dependencies'...
[10:52:45] gulp-notify: [Gulp notification] Compile Sass File: style.scss...
events.js:141

      throw er; // Unhandled 'error' event
      ^

Error: Error: Cannot find where you keep your Bower packages.
    at /Users/andrewkeller/dev/electron-angular-boilerplate/node_modules/wiredep/wiredep.js:30:56
    at findBowerDirectory (/Users/andrewkeller/dev/electron-angular-boilerplate/node_modules/wiredep/wiredep.js:109:27)
    at wiredep (/Users/andrewkeller/dev/electron-angular-boilerplate/node_modules/wiredep/wiredep.js:37:43)
    at DestroyableTransform._transform (/Users/andrewkeller/dev/electron-angular-boilerplate/node_modules/wiredep/wiredep.js:136:34)
    at DestroyableTransform.Transform._read (/Users/andrewkeller/dev/electron-angular-boilerplate/node_modules/wiredep/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/Users/andrewkeller/dev/electron-angular-boilerplate/node_modules/wiredep/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/Users/andrewkeller/dev/electron-angular-boilerplate/node_modules/wiredep/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/Users/andrewkeller/dev/electron-angular-boilerplate/node_modules/wiredep/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at DestroyableTransform.Writable.write (/Users/andrewkeller/dev/electron-angular-boilerplate/node_modules/wiredep/node_modules/readable-stream/lib/_stream_writable.js:194:11)
    at write (/Users/andrewkeller/dev/electron-angular-boilerplate/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:623:24)

npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/Users/andrewkeller/.npm-packages/bin/npm" "start"
npm ERR! node v4.2.4
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE
npm ERR! electron-angular-boilerplate@1.5.0 start: `gulp && electron .`
npm ERR! Exit status 1

npm ERR!
npm ERR! Failed at the electron-angular-boilerplate@1.5.0 start script 'gulp && electron .'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron-angular-boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp && electron .
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron-angular-boilerplate
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron-angular-boilerplate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/andrewkeller/dev/electron-angular-boilerplate/npm-debug.log
```

Do @Stephn-R 's suggestion for the node-sass failure:

```
sudo npm i -g node-sass
sudo npm rebuild node-sass
```

Same error as above...

Look to the open issues and find [#17](https://github.com/Stephn-R/electron-angular-boilerplate/issues/14), realize this is a new computer and I don't have bower installed globally. 

```
npm install bower -g
bower install
```

Successful bower install:

```
bower                     invalid-meta The "name" is recommended to be lowercase, can contain digits, dots, dashes
bower angular-mocks#1.4.9   not-cached https://github.com/angular/bower-angular-mocks.git#1.4.9
bower angular-mocks#1.4.9      resolve https://github.com/angular/bower-angular-mocks.git#1.4.9
bower skeleton#2.0.4        not-cached https://github.com/dhgamache/Skeleton.git#2.0.4
bower skeleton#2.0.4           resolve https://github.com/dhgamache/Skeleton.git#2.0.4
bower angular#1.4.9         not-cached https://github.com/angular/bower-angular.git#1.4.9
bower angular#1.4.9            resolve https://github.com/angular/bower-angular.git#1.4.9
bower skeleton#2.0.4          checkout 2.0.4
bower angular-mocks#1.4.9     checkout v1.4.9
bower angular#1.4.9           checkout v1.4.9
bower skeleton#2.0.4          resolved https://github.com/dhgamache/Skeleton.git#2.0.4
bower angular-mocks#1.4.9     resolved https://github.com/angular/bower-angular-mocks.git#1.4.9
bower angular#1.4.9           resolved https://github.com/angular/bower-angular.git#1.4.9

bower skeleton#2.0.4           install skeleton#2.0.4
bower angular-mocks#1.4.9      install angular-mocks#1.4.9
bower angular#1.4.9            install angular#1.4.9

skeleton#2.0.4 dist/vendor/skeleton

angular-mocks#1.4.9 dist/vendor/angular-mocks
└── angular#1.4.9

angular#1.4.9 dist/vendor/angular
```

Hit it with an 

```
npm start
```

Errors out because I do not have electron installed globally:

```
$ npm start

> electron-angular-boilerplate@1.5.0 start /Users/andrewkeller/dev/electron-angular-boilerplate
> gulp && electron .

[11:02:31] Using gulpfile ~/dev/electron-angular-boilerplate/gulpfile.js
[11:02:31] Starting 'build-sass'...
[11:02:33] Starting 'inject-dependencies'...
[11:02:33] gulp-notify: [Gulp notification] Compile Sass File: style.scss...
[11:02:33] Finished 'inject-dependencies' after 128 ms
[11:02:33] Finished 'build-sass' after 1.55 s
[11:02:33] Starting 'default'...
[11:02:33] Transposing Sass...
[11:02:33] Finished 'default' after 217 μs
sh: electron: command not found


npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/Users/andrewkeller/.npm-packages/bin/npm" "start"
npm ERR! node v4.2.4
npm ERR! npm  v3.10.5
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! electron-angular-boilerplate@1.5.0 start: `gulp && electron .`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the electron-angular-boilerplate@1.5.0 start script 'gulp && electron .'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron-angular-boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp && electron .
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron-angular-boilerplate
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron-angular-boilerplate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/andrewkeller/dev/electron-angular-boilerplate/npm-debug.log
```

Think to myself, boy we really need to get this lib off global dependencies!
Anyway, I install electron globally:

```
npm install electron-prebuilt@1.2.2 -g
```

Finally... Success!

**Comment by andrewjaykeller** [comment]
Why did the `postinstall` not pick up to install `bower`?

**Pull request closed without merging**
