### PR TITLE
Bump electron version to 1.2.2

### PR DESCRIPTION
**Pull request by devsli**
Fixes error when running `npm start`:

```
App threw an error during load
Error: Cannot find module 'app'
    at Module._resolveFilename (module.js:438:15)
    at Function.Module._resolveFilename (/usr/local/lib/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/electron.asar/common/reset-search-paths.js:47:12)
    at Function.Module._load (module.js:386:25)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/sli/spreenauten/electron-angular-boilerplate/main.js:4:11)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
```

### CODE REVIEW

**Comment by rpocklin** [comment]
Thanks, just installed it and needed this patch to get it to work.  Please accept @Stephn-R

**Comment by andrewjaykeller** [comment]
Hey @rpocklin @Stephn-R is not maintaining this project any more, he made me a contributor though to keep it going so I will pull this and check it out!

**Comment by andrewjaykeller** [comment]
@devsli can you please change the base for this PR to `develop`

**Comment by devsli** [comment]
@pushtheworldllc done, check out #21

**Comment by stephnr** [comment]
@pushtheworldllc I am still alive

**Comment by andrewjaykeller** [comment]
@Stephn-R :)

**Pull request closed without merging**
